# dynamics model configuration
seed: 1
gen_len: 5
dynamics_model:
    _target_: mbrl.models.GaussianMLP
    device: ???
    num_layers: 3
    ensemble_size: 7
    hid_size: 200
    in_size: ???
    out_size: ???
    deterministic: False
    propagation_method: random_model
    activation_fn_cfg:
        _target_: torch.nn.SiLU


# options for training the dynamics model
algorithm:
    learned_rewards: False
    target_is_delta: True
    normalize: False

# these are experiment specific options
overrides:
    trial_length: ???
    num_steps: ???
    model_batch_size: 1
    validation_ratio: 0.05
    seed: 0

