# @package _group_
name: "pets_morph"
gen_len: 5
agent:
    _target_: mbrl.planning.OLOptimizerAgent
    planning_horizon: 15
    replan_freq: 1
    verbose: False
    action_lb: ???
    action_ub: ???
    environment_params_lb: ???
    environment_params_ub: ???
    initial_planning_horizon: 15


    # this is the optimizer to generate and choose a trajectory
    ol_optimizer_cfg:
        _target_: mbrl.planning.MorphCEMOptimizer
        num_iterations: 5
        elite_ratio: 0.1
        population_size: 210
        alpha: 0.1
        device: ???
        lower_bound: ???
        upper_bound: ???
        return_mean_elites: True


    il_optimizer_cfg:
        _target_: mbrl.planning.CEMOptimizer
        num_iterations: 5
        elite_ratio: 0.1
        population_size: 210
        alpha: 0.1
        device: ???
        lower_bound: ???
        upper_bound: ???
        return_mean_elites: True

normalize: true
normalize_double_precision: true
target_is_delta: true
initial_exploration_steps: ${overrides.trial_length}
freq_train_model: ${overrides.freq_train_model}
learned_rewards: ${overrides.learned_rewards}

num_particles: 20
